version: 0.2
phases: 
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - make build
  post_build:
    commands:
      - echo Build completed on `date`